### PR TITLE
Add debian/python3-libpam-fingerprint.install

### PR DESCRIPTION
**Pull request by hangingman**
A trial pull request; 
I wonder it might be caused by debhelper or pybuild version , or linux distribution.  If you have better solution, please tell me and close this PR.

## problem
- My environment
    - Debian12 (bookworm)
    - using system python3 (3.11)

On my environment, after exec `dpkg-buildpackage -uc -us` , deb package doesn't contain python sources.
I notice it because after installed `libpam-fingerprint_1.6_all.deb` , pamfingerprint-conf is not found.

## solution
- After added `debian/python3-libpam-fingerprint.install` in source tree,  exec `dpkg-buildpackage -uc -us` , and I could get a complete package containing all python sources.

```shell
dpkg-deb -c ../libpam-fingerprint_1.6_all.deb 
drwxr-xr-x root/root         0 2023-07-03 04:25 ./
drwxr-xr-x root/root         0 2023-07-03 04:25 ./etc/
-rw-r--r-- root/root       277 2023-07-03 04:25 ./etc/pamfingerprint.conf
drwxr-xr-x root/root         0 2023-07-03 04:25 ./lib/
drwxr-xr-x root/root         0 2023-07-03 04:25 ./lib/security/
-rw-r--r-- root/root      7343 2023-07-03 04:25 ./lib/security/pam_fingerprint.py
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/bin/
-rwxr-xr-x root/root     12031 2023-07-03 04:25 ./usr/bin/pamfingerprint-conf
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/lib/
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/lib/python3/
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/lib/python3/dist-packages/
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/lib/python3/dist-packages/libpam_fingerprint-1.6.egg-info/
-rw-r--r-- root/root       498 2023-07-03 04:25 ./usr/lib/python3/dist-packages/libpam_fingerprint-1.6.egg-info/PKG-INFO
-rw-r--r-- root/root         1 2023-07-03 04:25 ./usr/lib/python3/dist-packages/libpam_fingerprint-1.6.egg-info/dependency_links.txt
-rw-r--r-- root/root         0 2023-07-03 04:25 ./usr/lib/python3/dist-packages/libpam_fingerprint-1.6.egg-info/requires.txt
-rw-r--r-- root/root        15 2023-07-03 04:25 ./usr/lib/python3/dist-packages/libpam_fingerprint-1.6.egg-info/top_level.txt
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/lib/python3/dist-packages/pamfingerprint/
-rw-r--r-- root/root       273 2023-07-03 04:25 ./usr/lib/python3/dist-packages/pamfingerprint/__init__.py
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/share/
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/share/bash-completion/
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/share/bash-completion/completions/
-rw-r--r-- root/root       425 2023-07-03 04:25 ./usr/share/bash-completion/completions/pamfingerprint
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/share/doc/
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/share/doc/libpam-fingerprint/
-rw-r--r-- root/root       537 2023-07-03 04:25 ./usr/share/doc/libpam-fingerprint/changelog.gz
-rw-r--r-- root/root      1029 2023-07-03 04:25 ./usr/share/doc/libpam-fingerprint/copyright
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/share/lintian/
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/share/lintian/overrides/
-rw-r--r-- root/root       132 2023-07-03 04:25 ./usr/share/lintian/overrides/libpam-fingerprint
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/share/man/
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/share/man/man1/
-rw-r--r-- root/root       538 2023-07-03 04:25 ./usr/share/man/man1/pamfingerprint-conf.1.gz
drwxr-xr-x root/root         0 2023-07-03 04:25 ./usr/share/pam-configs/
-rw-r--r-- root/root       132 2023-07-03 04:25 ./usr/share/pam-configs/fingerprint
```

### CODE REVIEW

**Comment by hangingman** [comment]
@philippmeisberger Hi, would you please take a look it ?

**Comment by philippmeisberger** [comment]
Hi @hangingman ,
sorry for the late response. Thanks for your PR. I only think that the README is wrong. The `cd ./pam-fingerprint/src/` is completely wrong since the Debian package is on top-level. That should fix the problem.

You created the new file `python3-libpam-fingerprint.install` (based on https://github.com/philippmeisberger/pam-fingerprint/blob/master/debian/libpam-fingerprint.install), but since the package is named `libpam-fingerprint` debuild should ignore that file if you build the package.

I am planning an official release (1.6) which you get via APT, soon. Thus building the latest release is not necessary. Thank you for reporting that Problem.

**Comment by philippmeisberger** [comment]
This should fix the problem: https://github.com/philippmeisberger/pam-fingerprint/commit/9ba65006370f310ac88a8a1e56ed88e8547e8667

Could you please tell me if this really fixes your problem? If it does, we can close this issue.

**Comment by hangingman** [comment]
@philippmeisberger 
Thank you! 
At first,  the problem is resolved. I could build package according to README.
And sorry, I couldn't reproduce my original issue...(it's mysterious)

>I am planning an official release (1.6) which you get via APT, soon. Thus building the latest release is not necessary. 

I'm looking forward to seeing to get this package by APT  !
BTW, I'm using this package in my PC.

**Pull request closed without merging**
